name: api

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
     - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Configure Ngrok
        run: |
          ./ngrok authtoken 2lLwH55Szr1ALu0JNVfhSLdn46P_2rfzNyqMU1AZdeXGHVYLu

      - name: Start Ngrok Tunnel
        run: ./ngrok tunnel --label edge=edghts_2lReKuel1jJhvqboHbEp33hjPB8 http://localhost:3000 &

      - name: Start The Code
        run: node index.js &

      - name: Keep Alive
        id: check_runs
        run: |
          echo "has_new_run=false" >> $GITHUB_OUTPUT
          while true; do
            sleep 1
            latest_run=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=1&status=queued&status=in_progress" | \
              jq -r '.workflow_runs[0].id')
            if [[ $latest_run != ${{ github.run_id }} ]]; then
              echo "has_new_run=true" >> $GITHUB_OUTPUT
              break
            fi
          done

      - name: Stop Workflow
        if: steps.check_runs.outputs.has_new_run == 'true'
        run: exit 0

      - name: Keep Alive
        if: steps.check_runs.outputs.has_new_run == 'false'
        run: sleep 60
